### ISSUE TITLE
modelSaveMatchObjBtwnTrials

### ISSUE THREAD

**Issue by jonasoa** [bahanonu/ciatah#105]
Hello,
I'm having an issue when I try to save my results from the cross-session cell alignment. When I try using modelSaveMatchObjBtwnTrials a gui pops up for me to select a folder to save my data. After having selected a folder then this pops up 
![Capture](https://user-images.githubusercontent.com/107865256/174616789-d22ae782-5a52-42d9-be99-856a2e90f935.PNG)

The issue is that when I try to look through the folder that I selected to save my data then the file is not there. How can I save the data, and how can I access the file?

**Comment by bahanonu** [comment]
Hi,

You can alternatively access the cross-session alignment data via the Matlab command line through the ciatah class property `globalIDStruct`, e.g. `obj.globalIDStruct`. Within this structure are fieldnames named after each animal used for cross-session alignment, e.g. `obj.globalIDStruct.m77`. See https://bahanonu.github.io/ciatah/pipeline_detailed_cross_session/#output-of-computematchobjbtwntrials.

Also, what is the current directory (e.g. `pwd` on command line) of MATLAB when you ran `modelSaveMatchObjBtwnTrials`? It is possible that the file was saved in a `private` sub-directory of a non-CIAtah folder if the current directory was different. If you do an `Everything` (voidtools.com) or similar search for `20220620_154905.mat` does the MAT-file come up as saved in your workstation?

I'll put out an update today to ensure that `obj.dataSavePath` always saves to CIAtah `private` sub-directory rather than use a relative path. Let me know if you have any other questions in the meantime.

**Comment by bahanonu** [comment]
Update pushed so that by default `modelSaveMatchObjBtwnTrials` will save to `private` folder within CIAtah directory (e.g. check by running `ciapkg.getDir()` in command window.
